#!/bin/bash

DATIME=$(date '+%d-%m-%Y %H:%M:%S');
MODIFIEDTAGLINE="# [$DATIME] This file has been modified automatically by docker-setup"
INTERFACE=`/sbin/route -n | grep "^0.0.0.0" | rev | cut -d' ' -f1 | rev`
IP=`ifconfig $INTERFACE | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep -v 255`
FILE=/usr/lib/systemd/system/docker.service.d/startup_options.conf

echo "My local IP is $IP"
echo "Applying to /etc/systemd/system/docker.service.d/startup_options.conf"

sed -i '$ d' $FILE
LASTLINE=`tail -1 $FILE`
NEWLASTLINE=`echo $LASTLINE | sed -En 's/##//p' | sed -En "s/CHANGEME/$IP/p"`

echo $NEWLASTLINE >> $FILE
echo "Replacing head line"
sed -i -e "1 s/^.*$/$MODIFIEDTAGLINE\n/" "$FILE"
echo "Config changed"

echo "Reloading daemons"
systemctl daemon-reload
echo "Restarting docker service"
systemctl restart docker.service
